### ISSUE TITLE
node-minify throw new Error(setting + ' is mandatory.'); on npm start

### ISSUE THREAD

**Issue by mattcdowning** [mrmrs/mnml#32]
## Initial output
node-minify deprecated Instantiate is no longer necessary.
new compressor.minify() is deprecated.
Please use:

  var compressor = require("node-minify");
  compressor.minify();

 node_modules/node-minify/lib/node-minify.js:30:3
node-minify deprecated type was renamed to compressor node_modules/node-minify/lib/node-minify.js:30:3
node-minify deprecated fileIn was renamed to input node_modules/node-minify/lib/node-minify.js:30:3
node-minify deprecated fileOut was renamed to output node_modules/node-minify/lib/node-minify.js:30:3
/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:201
    throw new Error(setting + ' is mandatory.');
    ^

Error: compressor is mandatory.
    at mandatory (/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:201:11)
    at /Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:188:5
    at Array.forEach (native)
    at checkMandatories (/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:187:5)
    at setup (/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:43:3)
    at new minify (/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/node-minify.js:31:14)
    at Object.<anonymous> (/Users/mattdowning/Desktop/test/index.js:31:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

## Updating index.js 
Per the deprecation errors, I updated index.js with this:
`compressor.minify({
    type: 'clean-css',
    input: './css/mnml.css',
    output: './css/mnml.min.css'
});` which cleans the output to:

node-minify deprecated type was renamed to compressor node_modules/node-minify/lib/node-minify.js:30:3
/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:201
    throw new Error(setting + ' is mandatory.');
    ^

Error: compressor is mandatory.
    at mandatory (/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:201:11)
    at /Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:188:5
    at Array.forEach (native)
    at checkMandatories (/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:187:5)
    at setup (/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/setup.js:43:3)
    at Object.minify (/Users/mattdowning/Desktop/test/node_modules/node-minify/lib/node-minify.js:31:14)
    at Object.<anonymous> (/Users/mattdowning/Desktop/test/index.js:31:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

## Anyone have ideas on how to fix?
I'm not sure how to update the node-minify type to compressor as indicated.

**Comment by mattcdowning** [comment]
Resolved! PR made https://github.com/mrmrs/mnml/pull/33
